svg = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">\n'
    '  <defs>\n'
    '    <radialGradient id="bg" cx="50%" cy="50%" r="65%">\n'
    '      <stop offset="0%"   stop-color="#ffcb2e"/>\n'
    '      <stop offset="55%"  stop-color="#d4700a"/>\n'
    '      <stop offset="100%" stop-color="#943e08"/>\n'
    '    </radialGradient>\n'
    '    <radialGradient id="tlGlow" cx="18%" cy="14%" r="65%">\n'
    '      <stop offset="0%"   stop-color="#ffe080" stop-opacity="0.32"/>\n'
    '      <stop offset="100%" stop-color="#ffe080" stop-opacity="0"/>\n'
    '    </radialGradient>\n'
    '    <linearGradient id="glassDome" x1="0" y1="0" x2="0" y2="1">\n'
    '      <stop offset="0%"   stop-color="#ffffff" stop-opacity="0.22"/>\n'
    '      <stop offset="50%"  stop-color="#ffffff" stop-opacity="0.04"/>\n'
    '      <stop offset="100%" stop-color="#ffffff" stop-opacity="0"/>\n'
    '    </linearGradient>\n'
    '    <radialGradient id="spec" cx="50%" cy="0%" r="42%">\n'
    '      <stop offset="0%"   stop-color="#ffffff" stop-opacity="0.18"/>\n'
    '      <stop offset="100%" stop-color="#ffffff" stop-opacity="0"/>\n'
    '    </radialGradient>\n'
    '    <filter id="textShadow" x="-10%" y="-10%" width="120%" height="130%">\n'
    '      <feDropShadow dx="4" dy="5" stdDeviation="6" flood-color="#3a1200" flood-opacity="0.55"/>\n'
    '    </filter>\n'
    '    <clipPath id="clip"><rect width="512" height="512" rx="112"/></clipPath>\n'
    '  </defs>\n'
    '  <rect width="512" height="512" rx="112" fill="url(#bg)"/>\n'
    '  <rect width="512" height="512" rx="112" fill="url(#tlGlow)"/>\n'
    '  <circle cx="256" cy="228" r="187" fill="none" stroke="#5a2205" stroke-width="2" opacity="0.20"/>\n'
    '  <circle cx="256" cy="228" r="174" fill="none" stroke="#5a2205" stroke-width="1" opacity="0.12"/>\n'
    '  <text x="256" y="262"\n'
    '        font-family="Futura, &apos;Century Gothic&apos;, &apos;Gill Sans&apos;, sans-serif"\n'
    '        font-size="212" font-weight="700" fill="#160800"\n'
    '        text-anchor="middle" dominant-baseline="middle"\n'
    '        filter="url(#textShadow)">ASK</text>\n'
    '  <text x="256" y="257"\n'
    '        font-family="Futura, &apos;Century Gothic&apos;, &apos;Gill Sans&apos;, sans-serif"\n'
    '        font-size="212" font-weight="700" fill="#ffe8a0" fill-opacity="0.12"\n'
    '        text-anchor="middle" dominant-baseline="middle">ASK</text>\n'
    '  <line x1="148" y1="370" x2="364" y2="370" stroke="#5a2205" stroke-width="2" opacity="0.45"/>\n'
    '  <text x="256" y="418"\n'
    '        font-family="Futura, &apos;Century Gothic&apos;, &apos;Gill Sans&apos;, sans-serif"\n'
    '        font-size="38" font-weight="500" fill="#4a1a02"\n'
    '        text-anchor="middle" dominant-baseline="middle" letter-spacing="2">Mirror Talk</text>\n'
    '  <ellipse cx="256" cy="170" rx="245" ry="185" fill="url(#glassDome)" clip-path="url(#clip)"/>\n'
    '  <ellipse cx="256" cy="48"  rx="142" ry="62"  fill="url(#spec)"     clip-path="url(#clip)"/>\n'
    '</svg>\n'
)

path = '/Users/tobi/PycharmProjects/pythonProject/ask-mirror-talk/wordpress/astra-child/pwa-icon.svg'
with open(path, 'w') as f:
    f.write(svg)

import xml.etree.ElementTree as ET
ET.parse(path)
print('OK — written', len(svg), 'bytes,', svg.count('\n'), 'lines')
