#!/usr/bin/env python3
"""
Integration test for shareable headline generation feature.

This script tests the full end-to-end flow of headline generation,
verifying that:
1. Headlines are generated by the LLM
2. Headlines meet quality criteria (specific, insightful, not vague)
3. Headlines are included in API responses
4. Fallback extraction works when LLM unavailable

Usage:
    python tests/test_shareable_headline_integration.py
"""

import sys
import os

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.qa.answer import (
    _generate_shareable_headline,
    _extract_best_sentence_headline,
    compose_answer,
)


def test_extraction_fallback():
    """Test that sentence extraction works as fallback."""
    print("\n" + "="*70)
    print("TEST 1: Sentence Extraction Fallback")
    print("="*70)
    
    test_cases = [
        {
            "answer": "Trust that your next right step will reveal itself when you need it. This wisdom applies everywhere.",
            "expected_contains": "Trust that your next"
        },
        {
            "answer": "Your relationships need attention more than they need perfection. Focus on presence, not performance.",
            "expected_contains": "Your relationships"
        },
        {
            "answer": "Notice what's already good in your connections before wondering what's missing. Gratitude grounds growth.",
            "expected_contains": "Notice what's already"
        }
    ]
    
    passed = 0
    for i, case in enumerate(test_cases, 1):
        result = _extract_best_sentence_headline(case["answer"])
        if case["expected_contains"] in result:
            print(f"✅ Test {i} PASSED")
            print(f"   Input: {case['answer'][:60]}...")
            print(f"   Headline: {result}")
            passed += 1
        else:
            print(f"❌ Test {i} FAILED")
            print(f"   Expected to contain: {case['expected_contains']}")
            print(f"   Got: {result}")
    
    print(f"\nExtraction tests: {passed}/{len(test_cases)} passed")
    return passed == len(test_cases)


def test_headline_quality_criteria():
    """Test that headlines meet quality standards."""
    print("\n" + "="*70)
    print("TEST 2: Headline Quality Criteria")
    print("="*70)
    
    good_headlines = [
        "What you have in this relationship right now is already worth protecting.",
        "Your relationships need attention more than they need perfection.",
        "Trust that your next right step will reveal itself when you need it.",
        "Notice what's already good before wondering what's missing.",
    ]
    
    bad_headlines = [
        "Be better.",  # Too short
        "This reflection reminds us to be present.",  # Meta-language
        "How do I fix this relationship?",  # Question
        "a",  # Way too short
    ]
    
    print("\n📊 Good Headlines (should all pass criteria):")
    good_passed = 0
    for headline in good_headlines:
        words = len(headline.split())
        length = len(headline)
        ends_properly = headline[-1] in ".!?"
        not_question = not headline.endswith("?")
        no_meta = "this reflection" not in headline.lower()
        
        if (40 <= length <= 180 and 6 <= words <= 26 and 
            ends_properly and not_question and no_meta):
            print(f"✅ {headline[:60]}...")
            good_passed += 1
        else:
            print(f"❌ {headline}")
            print(f"   Length: {length}, Words: {words}, Ends: {ends_properly}, "
                  f"NotQ: {not_question}, NoMeta: {no_meta}")
    
    print(f"\n📊 Bad Headlines (should all fail criteria):")
    bad_passed = 0
    for headline in bad_headlines:
        words = len(headline.split())
        length = len(headline)
        ends_properly = headline[-1] in ".!?" if headline else False
        
        if not (40 <= length <= 180 and 6 <= words <= 26 and ends_properly):
            print(f"✅ Correctly rejected: {headline}")
            bad_passed += 1
        else:
            print(f"❌ Should have rejected: {headline}")
    
    total_passed = good_passed + bad_passed
    total = len(good_headlines) + len(bad_headlines)
    print(f"\nQuality criteria tests: {total_passed}/{total} passed")
    return total_passed == total


def test_compose_answer_integration():
    """Test that compose_answer includes shareable headline."""
    print("\n" + "="*70)
    print("TEST 3: Integration with compose_answer()")
    print("="*70)
    
    # Mock chunks that would come from the database
    chunks = [
        {
            "text": "Your relationships need presence more than perfection. When you focus on being genuinely available rather than performing flawlessly, connection deepens naturally.",
            "start_time": 120,
            "end_time": 150,
            "episode": {
                "id": 1,
                "title": "The Power of Presence in Relationships",
                "audio_url": "http://example.com/audio.mp3",
                "published_year": 2024,
            },
        }
    ]
    
    question = "How do I strengthen my relationships?"
    
    print(f"\nQuestion: {question}")
    print("Calling compose_answer...")
    
    try:
        # This will attempt to call OpenAI if configured
        # Otherwise it will use extraction fallback
        result = compose_answer(question, chunks, include_followups=True)
        
        print(f"\n✅ compose_answer() executed successfully")
        print(f"   Answer preview: {result['answer'][:100]}...")
        print(f"   Citations: {len(result['citations'])}")
        print(f"   Follow-up questions: {len(result['follow_up_questions'])}")
        print(f"   Shareable headline: {result.get('shareable_headline', 'NOT FOUND')}")
        
        # Verify shareable_headline is present
        if 'shareable_headline' in result:
            headline = result['shareable_headline']
            if headline:
                print(f"\n✅ Headline generated: {headline}")
                return True
            else:
                print(f"\n⚠️  Headline field present but empty (expected if OpenAI disabled)")
                return True
        else:
            print(f"\n❌ shareable_headline field missing from result")
            return False
            
    except Exception as e:
        print(f"\n❌ Error during compose_answer: {e}")
        import traceback
        traceback.print_exc()
        return False


def test_real_headline_generation():
    """Test headline generation with realistic examples."""
    print("\n" + "="*70)
    print("TEST 4: Real Headline Generation")
    print("="*70)
    
    test_cases = [
        {
            "question": "How do I handle grief?",
            "answer": "Grief asks for space, not solutions. What you need most is permission to feel whatever comes, without rushing toward some imagined finish line. The work of grief is allowing what's broken to be broken while trusting that healing happens in its own time, not on a schedule you set.",
            "chunks": [{"episode": {"title": "Understanding Grief"}, "text": "Grief needs space and permission"}],
        },
        {
            "question": "How can I set better boundaries?",
            "answer": "Boundaries aren't walls you build to keep others out; they're clarity you offer about what you need to stay present and whole. When you honor your own limits with the same respect you'd give a friend's, relationships become sustainable instead of draining.",
            "chunks": [{"episode": {"title": "The Art of Boundaries"}, "text": "Boundaries are clarity, not walls"}],
        },
    ]
    
    passed = 0
    for i, case in enumerate(test_cases, 1):
        print(f"\n📝 Test Case {i}:")
        print(f"   Question: {case['question']}")
        
        try:
            headline = _generate_shareable_headline(
                case['question'],
                case['answer'],
                case['chunks']
            )
            
            print(f"   Generated: {headline}")
            
            # Check basic quality
            if len(headline) >= 30 and headline.endswith((".","!","?")):
                print(f"   ✅ Quality check passed")
                passed += 1
            else:
                print(f"   ⚠️  Quality check: headline may be too short or improperly formatted")
                passed += 0.5  # Partial credit
                
        except Exception as e:
            print(f"   ❌ Error: {e}")
    
    print(f"\nReal generation tests: {passed}/{len(test_cases)} passed")
    return passed >= len(test_cases) * 0.7  # Allow for some partial credit


def main():
    """Run all integration tests."""
    print("\n" + "="*70)
    print("🧪 SHAREABLE HEADLINE INTEGRATION TEST SUITE")
    print("="*70)
    
    results = {
        "Extraction Fallback": test_extraction_fallback(),
        "Quality Criteria": test_headline_quality_criteria(),
        "compose_answer Integration": test_compose_answer_integration(),
        "Real Generation": test_real_headline_generation(),
    }
    
    print("\n" + "="*70)
    print("📊 TEST SUMMARY")
    print("="*70)
    
    for test_name, passed in results.items():
        status = "✅ PASS" if passed else "❌ FAIL"
        print(f"{status}: {test_name}")
    
    passed_count = sum(1 for passed in results.values() if passed)
    total_count = len(results)
    
    print(f"\nTotal: {passed_count}/{total_count} test suites passed")
    print("="*70)
    
    if passed_count == total_count:
        print("\n🎉 All integration tests passed!")
        return 0
    else:
        print(f"\n⚠️  {total_count - passed_count} test suite(s) failed")
        return 1


if __name__ == "__main__":
    sys.exit(main())
